### ISSUE TITLE
About the torch version issue

### ISSUE THREAD

**Issue by Qinulinuli** [BojarLab/SweetNet#2]
Hello, 
  after installing torch=1.7.0, cuda=10.2, and the corresponding latest torch-sparse，torch-scatter，torch-cluster and torch-spline-conv, the following error occurred in the running code. Could you tell me the correct version of torch.
![56](https://user-images.githubusercontent.com/116611946/227929700-3e4705d3-f6e3-425e-a5cd-22d2e658b8f7.png)

**Comment by Bribak** [comment]
Hi there & thanks for your interest!
As stated in the Readme of this repo, you should use the SweetNet version within our glycowork package (its documentation at https://bojarlab.github.io/glycowork/ also contains all current info about the relevant torch versions).
The SweetNet repo as such only exists for documentation purposes and is not actively maintained. The glycowork versions are actively maintained, so any issues should be posted there.

The snippet we currently use internally is:
`!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.13.0+cu116.html
!pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.13.0+cu116.html
!pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.13.0+cu116.html
!pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.13.0+cu116.html
!pip install torch-geometric==2.2.0`

(but again, note that this will not work with the code from this repo, as this is 2 years out of date)

**Comment by Qinulinuli** [comment]
thank you
